name: AGVisualDesign
favicon: null
layout_spectrum: 0.18673647358082235
typography_spectrum: 0.13458402268588543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2784482731949538
  lightness: 0.015186713309958577
  saturation: 0.5073708621785045
  rhythmicContrast: 0.17616077326238155
purpose: []
